# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x64'

- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'test_test1.py'
- script: |
    python -m pip install --upgrade pip
    python3 -m venv task
    source task/bin/activate
    pip3 install -r requirements.txt
    pip3 list
    deactivate
  displayName: 'Edit Env'
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'omar@40.121.41.196'
    contents: 'requirements.txt'
    targetFolder: '/home/omar'
    readyTimeout: '20000'
    
      


