# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: SSH@0
  inputs:
    sshEndpoint: 'omar@40.121.41.196'
    runOptions: 'commands'
    commands: 'ls /home'
    readyTimeout: '20000'
- task: SSH@0
  inputs:
    sshEndpoint: 'omar@40.121.41.196'
- task: SSH@0
  inputs:
    sshEndpoint: 'omar@40.121.41.196'
    runOptions: 'commands'
    commands: 'rm -rf test101'
    readyTimeout: '20000'
- task: SSH@0
  inputs:
    sshEndpoint: 'omar@40.121.41.196'
    runOptions: 'commands'
    commands: 'mkdir test101'
    readyTimeout: '20000'
- task: SSH@0
  inputs:
    sshEndpoint: 'omar@40.121.41.196'
    runOptions: 'commands'
    commands: 'mkdir test111'
    readyTimeout: '20000'